name: Test

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
  workflow_dispatch:

jobs:
  sco-server:
    name: sco-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.27'
          check-latest: true
          cache-dependency-path: "**/*.sum"

      - name: Install dependencies
        run: go work sync

      - name: Build
        run: ./build.sh

      - uses: actions/upload-artifact@v7
        with:
          name: sco-artifacts
          path: ./build/
